# Generated by Django 6.0.7 on 2026-08-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='Avg',
            field=models.FloatField(default=0.0),
        ),
    ]
